made changes to CriteriaRepoTest.java
revaturelabs/forge-review-service pull request #24
Opened 2021-01-08 17:25 UTC by esratjahan12

Create Mockito test for CriteriaRepoTest.java. Don't delete, High Priority.

2021-01-08 21:18 UTC, KennethDavis391 requested changes
please remove the repo tests.

2021-01-08 21:18 UTC, KennethDavis391 commented on Portfolio-Review-Service/src/test/java/PortfolioReviewService/repo/CriteriaRepoTest.java
> +	@Test
These tests aren't actually testing anything, they literally cannot fail. You're mocking the methods you test. That being said, there's no need to test jpa repositories. If you wanted to do some thing similar, you could mock the repo in the service tests and verify the number of times certain methods from the repo were called.

2021-01-09 00:01 UTC, foshaystephanie approved these changes
approved after CriteriaRepoTest removed.

2021-01-11 17:42 UTC, KennethDavis391 approved these changes

2021-01-11 22:06 UTC, merged